config/routes.rb
# application routes 
Rails.application.routes.draw do
  get 'orders/new'
  resources :products
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  get "orders", to: "orders#new", as: "new_order"
  post "/orders/webhook", to: "orders#webhook"
  get "/orders/complete", to: "orders#complete"
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "/reviews/", to: "reviews#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
    has_many :reviews, dependent: :destroy

    def get_average_rating
        Review.get_average_rating(self)
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  


  def self.get_average_rating(product)
    reviews = Review.select(:rating).where(product_id: product.id)
    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    return 0 if sum == 0
    rating = (sum.to_f / reviews.length).round(2)
    return rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products, dependent: :destroy
  has_many :reviews, through: :products

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # New Product Method to add products
  def new
    @product = Product.find(params[:product_id])
    @session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [{
      name: @product.name,
      amount: (@product.price * 100).to_i,
      currency: 'aud',
      quantity: 1,
    }],
    payment_intent_data: {
      metadata: {
        user_id: current_user.id,
        product_id: @product.id
      }
    },
    success_url: "#{root_url}orders/complete",
    cancel_url: "#{root_url}",
    )
  end

  # Method to check payment is succesful
  def webhook
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    product_id = payment.metadata.product_id
    user_id = payment.metadata.user_id
    p "product id #{product_id}"
    p "user id #{user_id}"
    render plain: "Success"
  end
 
  def complete
  end
 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = @product.reviews
    @rating = Review.get_average_rating(@product)
  end

  # GET /products/new
  def new
    @product = Product.new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.picture.attach(params[:product][:picture])
    
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price, :farm, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
        @review.product_id = params[:product]
    end
    def create
        product = Product.find(params[:review][:product_id])
        @review = product.reviews.new
        @review.user_id = current_user.id
        @review.rating = params[:review][:rating]
        @review.comment = params[:review][:comment]
        if @review.save
          redirect_to product_path(product)
        else
          flash[:alert] = "Ooops. There was a problem creating the review."
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketplaceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%# top navigation  %>
        <div class="row float-right">
          <%= render "shared/topnav" %>
        </div>

        <%# side navigation %>
        <div class="row">
          <div class="col-2">
            <%= render "shared/sidenav" %>
          </div>
        </div>

    <%# main page container  %>
    <div class="container"> 
      <%= yield %>
    </div>

  </body>
</html>

app/views/orders/complete.html.erb
<%# completed orders view %>
<h1>Thank you for your purchase</h1>

app/views/orders/new.html.erb
<h1 class="list-item"> Your order
</h1>
<table>
<thead> <tr>
     <th>Name</th>
     <th>Quantity</th>
     <th>Price</th>
   </tr>
 </thead>
<tbody> <tr>
<td><%= @product.name %></td>
<td><%= @product.quantity %></td>
<td><%= number_to_currency @product.price %></td>
   </tr>
 </tbody>
</table>
<button id="pay-now">Checkout now</button>
<%= link_to "Back", :back %>
<br>

<script src="https://js.stripe.com/v3/"></script>
<script>
 document
   .querySelector("[id='pay-now']")
   .addEventListener("click", () => {
     const stripe = Stripe(
       "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
     );

     stripe.redirectToCheckout({
       sessionId: "<%= @session.id %>"
     });
   });
</script>
<br>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# form fields  %>
    <div class="field">
    <%= form.hidden_field :user_id %>
    </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :farm %>
    <%= form.text_field :farm %>
  </div>

  <div class="field">
       <%= form.label :picture %>
       <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'View', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Produce available</h1>
<br>

<%# Product table %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Farm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.farm %></td>
        <%# main button links  %>
        <td><%= link_to 'View', product, class:"btn btn-primary" %></td>
        <%# <% if current_user == product.user_id?  check this line for errors%>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-warning"  %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/products/new.html.erb
<h1>New Product Listing</h1>
<br>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
<br>
<br>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Farm:</strong>
  <%= @product.farm %>
</p>

  <% if @product.picture.attached? %>
    <%= image_tag @product.picture %>
  <% end %>
  
<%= link_to "Buy now", new_order_path(product_id: @product.id), class:"btn btn-success" %>
<%= link_to 'Back', products_path, class:"btn btn-secondary" %>
  <% if current_user.id == @product.user_id %>
        <td><%= link_to 'Edit', edit_product_path(@product), class:"btn btn-warning" %></td>
        <td><%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
  <% end %>

  <div>
 <h3>Reviews</h3>
 <% if user_signed_in? %>
        <%= link_to 'Add a review', new_review_path(product: @product), class:"btn btn-dark"%>
      <% else %>
        <%= link_to "Sign in to add a review!", new_user_registration_path, class:"btn btn-dark" %>
      <% end %>
 <p>Overall Rating: <%= @rating%> </p>
 <%if @reviews%>
   <%@reviews.each do |review|%>
     <div>
       <p class="rating"><%= "Rating: #{review.rating}"%></p>
       <p><%= review.user.email%>: <%= review.comment %></p>
     </div>
   <%end%>
 <%end%>
</div>

app/views/reviews/new.html.erb
<h1><%= "Review for #{@review.product.name}"%></h1>
<%=form_with model: @review do |form|%>
<%= form.hidden_field :product_id%>
<p>
 <%= label :rating, 'Rating' %>
 <%= form.number_field :rating, min: 1, max: 5, required: true %>
</p>
<p>
 <%=label :comment, 'Comments'%>
 <%= form.text_area :comment %>
</p>
<%= form.submit "Add review", class:"btn btn-dark"%>
<p class="link item-link"><%= link_to 'Cancel', :back %>
<%end%>

app/views/shared/_sidenav.html.erb
<%# side navigation bar  %>
<div class="sidenav">
<p><%= link_to "Home Page", root_path %></p>
<% if user_signed_in? %>
<p><%= link_to "Buy Produce", products_path %></p>
<p><%= link_to "Sell Produce", new_product_path %></p>
<% end %>
</div>

app/views/shared/_topnav.html.erb
<%# top navigation bar  %>
<header class="top-nav row align-items-end">
    <div class="col text-right">
        <% if user_signed_in? %>
        <div id="logout"><%= link_to 'Logout', destroy_user_session_path, method: "delete",class:"top-nav-link"%>|
        <%= current_user.email %></div>
        <% else %>
        <p><%= link_to 'Login', new_user_session_path, class:"top-nav-link"%>
        |
        <%= link_to 'Sign Up', new_user_registration_path, class:"top-nav-link"%>
        </p>
        <% end %>
    </div>
</header>

app/views/welcome/index.html.erb
<%# index page view  %>
<h1>Welcome to Farm 2 Table</h1>
<p>Mission Statement - We are here for the Farmers and we are here for the Customers. For too long now large coperations have had a firm grasp on the Fresh Produce Market. 
<br>
<br> We are here to disrupt the market and provide an easy to use and simple to navigate intrerface to BUY... or SELL fresh produce.</p>
<p>Please join us today and sign up above.</p>